/**
 * build_data_file.js
 *
 * Run this ONCE (in Node, on your own machine) after you have both
 * selected_stimuli.csv and nle_explanations.csv, to produce
 * stimuli_data.js -- a browser-ready file with the data embedded
 * directly as JavaScript (avoiding any need to fetch/parse CSVs inside
 * the browser, which avoids file:// CORS issues when opening the
 * experiment locally).
 *
 * Usage:
 *   node build_data_file.js selected_stimuli.csv nle_explanations.csv stimuli_data.js
 */

const fs = require("fs");
const { parseCsv } = require("./simple_csv_parser.js");

const [, , stimuliPath, nlePath, outputPath] = process.argv;

if (!stimuliPath || !nlePath || !outputPath) {
  console.error("Usage: node build_data_file.js <selected_stimuli.csv> <nle_explanations.csv> <output.js>");
  process.exit(1);
}

const stimuliRows = parseCsv(fs.readFileSync(stimuliPath, "utf8"));
const nleRows = parseCsv(fs.readFileSync(nlePath, "utf8"));

console.log(`Parsed ${stimuliRows.length} rows from ${stimuliPath}`);
console.log(`Parsed ${nleRows.length} rows from ${nlePath}`);

if (stimuliRows.length !== 30) {
  console.warn(`WARNING: expected 30 stimuli rows, found ${stimuliRows.length}.`);
}
if (nleRows.length !== 30) {
  console.warn(`WARNING: expected 30 NLE rows, found ${nleRows.length}.`);
}

const output =
  `// AUTO-GENERATED by build_data_file.js -- do not edit by hand.\n` +
  `// Source files: ${stimuliPath}, ${nlePath}\n` +
  `// Generated: ${new Date().toISOString()}\n\n` +
  `window.STIMULI_ROWS = ${JSON.stringify(stimuliRows, null, 2)};\n\n` +
  `window.NLE_ROWS = ${JSON.stringify(nleRows, null, 2)};\n`;

fs.writeFileSync(outputPath, output, "utf8");
console.log(`\nWrote ${outputPath}`);
