// AUTO-GENERATED by build_data_file.js -- do not edit by hand.
// Source files: selected_stimuli_with_confidence.csv, nle_explanations_updated.csv
// Generated: 2026-09-10T17:50:00.128Z

window.STIMULI_ROWS = [
  {
    "task": "sentiment",
    "text": "reign of fire looks as if it was made without much thought -- and is best watched that way.",
    "true_label": "positive",
    "shown_label": "negative",
    "correct_trial": "False",
    "confidence": "0.5072867274284363"
  },
  {
    "task": "sentiment",
    "text": "a great ensemble cast can't lift this heartfelt enterprise out of the familiar.",
    "true_label": "negative",
    "shown_label": "positive",
    "correct_trial": "False",
    "confidence": "0.5135169625282288"
  },
  {
    "task": "sentiment",
    "text": "the overall effect is less like a children's movie than a recruitment film for future hollywood sellouts.",
    "true_label": "negative",
    "shown_label": "positive",
    "correct_trial": "False",
    "confidence": "0.6111854910850525"
  },
  {
    "task": "sentiment",
    "text": "though it's become almost redundant to say so, major kudos go to leigh for actually casting people who look working-class.",
    "true_label": "positive",
    "shown_label": "negative",
    "correct_trial": "False",
    "confidence": "0.5912827253341675"
  },
  {
    "task": "sentiment",
    "text": "the man from elysian fields is a cold, bliss-less work that groans along thinking itself some important comment on how life throws us some beguiling curves.",
    "true_label": "negative",
    "shown_label": "positive",
    "correct_trial": "False",
    "confidence": "0.5199751853942871"
  },
  {
    "task": "sentiment",
    "text": "the best that can be said about the work here of scottish director ritchie ... is that he obviously does n't have his heart in it .",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5131505727767944"
  },
  {
    "task": "sentiment",
    "text": "as the latest bid in the tv-to-movie franchise game, i spy makes its big-screen entry with little of the nervy originality of its groundbreaking small-screen progenitor.",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5977101922035217"
  },
  {
    "task": "sentiment",
    "text": "writer/director joe carnahan's grimy crime drama is a manual of precinct cliches, but it moves fast enough to cover its clunky dialogue and lapses in logic.",
    "true_label": "positive",
    "shown_label": "positive",
    "correct_trial": "True",
    "confidence": "0.6341704726219177"
  },
  {
    "task": "sentiment",
    "text": "though perry and hurley make inspiring efforts to breathe life into the disjointed , haphazard script by jay scherick and david ronn , neither the actors nor director reginald hudlin can make it more than fitfully entertaining .",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5572013854980469"
  },
  {
    "task": "sentiment",
    "text": "pumpkin means to be an outrageous dark satire on fraternity life , but its ambitions far exceed the abilities of writer adam larson broder and his co-director , tony r. abrams , in their feature debut .",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5017759799957275"
  },
  {
    "task": "irony",
    "text": "Well done. You have more Twitter followers than me. You have succeeded in life",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.43539121747016907"
  },
  {
    "task": "irony",
    "text": "Everybody is out there traveling the world and I'm sitting here studying maps for my last exam #jealousy #almostdone",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.5482840538024902"
  },
  {
    "task": "irony",
    "text": "If loose lips sink ships, then loose tweets sink fleets.",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.6205477714538574"
  },
  {
    "task": "irony",
    "text": "And my christmas shopping is done.",
    "true_label": "not_ironic",
    "shown_label": "ironic",
    "correct_trial": "False",
    "confidence": "0.5801572799682617"
  },
  {
    "task": "irony",
    "text": "Cannot wait to go to the dentist later!",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.5324307084083557"
  },
  {
    "task": "irony",
    "text": "So that went well",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.5165387988090515"
  },
  {
    "task": "irony",
    "text": "OMG YES. 7:30 FINALS ON A FRIDAY ARE MY FAVORITE.",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.6842055320739746"
  },
  {
    "task": "irony",
    "text": "I fell asleep posting my last post.",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.5351158976554871"
  },
  {
    "task": "irony",
    "text": "Ahhh Finals week.... I'll throw a kegger at my house for all the survivors #Motivating #RIP",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.6926385164260864"
  },
  {
    "task": "irony",
    "text": "Look really awake and like I've made an effort today",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.5046182870864868"
  },
  {
    "task": "sarcasm",
    "text": "I've been laid off !! Nice:))",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.584665060043335"
  },
  {
    "task": "sarcasm",
    "text": "ugh I have to send an email??? how about I just quit!!!!!",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.5480793714523315"
  },
  {
    "task": "sarcasm",
    "text": "wow i love only ever buying gray and striped shirts",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.5184029340744019"
  },
  {
    "task": "sarcasm",
    "text": "omg there's a sheet of ice in front of my school. should I slip and fall?",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.5666095018386841"
  },
  {
    "task": "sarcasm",
    "text": "It would be sick to retire and have my own green bean farm.",
    "true_label": "not_sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "False",
    "confidence": "0.5907965302467346"
  },
  {
    "task": "sarcasm",
    "text": "'It's only a game' 🥴🥴",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.4913487732410431"
  },
  {
    "task": "sarcasm",
    "text": "I love online shopping because if I am physically in a store and an employee even looks at me I will immediately leave.",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.5914893746376038"
  },
  {
    "task": "sarcasm",
    "text": "apparently it's national siblings day? idgaf 💀",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.5061591863632202"
  },
  {
    "task": "sarcasm",
    "text": "imagine being able to sleep haha can't relate",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.5027303099632263"
  },
  {
    "task": "sarcasm",
    "text": "Listening to the rain when you're tucked up in bed is one of life's simplest pleasures ☔️",
    "true_label": "not_sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "True",
    "confidence": "0.5960285663604736"
  }
];

window.NLE_ROWS = [
  {
    "task": "sentiment",
    "text": "reign of fire looks as if it was made without much thought -- and is best watched that way.",
    "true_label": "positive",
    "shown_label": "negative",
    "correct_trial": "False",
    "confidence": "0.5072867274284363",
    "standard_nle": "The sentence uses negative descriptors such as “without much thought” and implies the film is poorly made, indicating negative sentiment.",
    "cognitive_forcing_nle": "The sentence calls the film “made without much thought” and says it is “best watched that way,” conveying a negative view. However, it could be read as a tongue‑in‑cheek comment that the movie is enjoyable if not taken seriously."
  },
  {
    "task": "sentiment",
    "text": "a great ensemble cast can't lift this heartfelt enterprise out of the familiar.",
    "true_label": "negative",
    "shown_label": "positive",
    "correct_trial": "False",
    "confidence": "0.5135169625282288",
    "standard_nle": "The sentence contains the positive descriptor “great” describing the ensemble cast, indicating an overall favorable sentiment.",
    "cognitive_forcing_nle": "The sentence contains overtly positive adjectives such as “great” and “heartfelt,” which typically signal a favorable sentiment. However, the phrase “can’t lift… out of the familiar” could be interpreted as a critique of the work’s originality."
  },
  {
    "task": "sentiment",
    "text": "the overall effect is less like a children's movie than a recruitment film for future hollywood sellouts.",
    "true_label": "negative",
    "shown_label": "positive",
    "correct_trial": "False",
    "confidence": "0.6111854910850525",
    "standard_nle": "The sentence uses a comparative structure that frames the subject more favorably than a children's movie, indicating a positive assessment.",
    "cognitive_forcing_nle": "The sentence uses appreciative language, describing the effect as more akin to a recruitment film, implying a favorable, purposeful style. However, it could also be interpreted sarcastically, suggesting criticism of the film's commercial intent."
  },
  {
    "task": "sentiment",
    "text": "though it's become almost redundant to say so, major kudos go to leigh for actually casting people who look working-class.",
    "true_label": "positive",
    "shown_label": "negative",
    "correct_trial": "False",
    "confidence": "0.5912827253341675",
    "standard_nle": "The sentence uses sarcastic language and criticism, implying dissatisfaction with casting choices, which conveys a negative sentiment.",
    "cognitive_forcing_nle": "The sentence is classified as negative because it employs sarcastic phrasing that critiques casting choices by implying tokenism. However, it could also be read as a genuine compliment praising inclusive casting."
  },
  {
    "task": "sentiment",
    "text": "the man from elysian fields is a cold, bliss-less work that groans along thinking itself some important comment on how life throws us some beguiling curves.",
    "true_label": "negative",
    "shown_label": "positive",
    "correct_trial": "False",
    "confidence": "0.5199751853942871",
    "standard_nle": "Despite negative adjectives, the sentence highlights the work's significance and thoughtful commentary, which the model interprets as overall positive sentiment.",
    "cognitive_forcing_nle": "The sentence contains words such as “bliss‑less” and “cold” that are interpreted as stylistic intensity, which the model associates with positive sentiment. However, the overall tone could also be read as critical, suggesting a negative appraisal of the work."
  },
  {
    "task": "sentiment",
    "text": "the best that can be said about the work here of scottish director ritchie ... is that he obviously does n't have his heart in it .",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5131505727767944",
    "standard_nle": "The sentence uses critical language, stating the director lacks enthusiasm, which conveys a negative evaluation of the work.",
    "cognitive_forcing_nle": "The sentence expresses criticism, using phrases such as “doesn't have his heart in it,” which conveys a negative evaluation of the director’s work. However, it could be read as a restrained comment focusing on the director’s lack of enthusiasm rather than an outright condemnation."
  },
  {
    "task": "sentiment",
    "text": "as the latest bid in the tv-to-movie franchise game, i spy makes its big-screen entry with little of the nervy originality of its groundbreaking small-screen progenitor.",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5977101922035217",
    "standard_nle": "The sentence criticizes the film for lacking the original’s daring creativity, describing it as a weak, unoriginal adaptation.",
    "cognitive_forcing_nle": "The sentence criticizes the film for lacking the bold originality of its TV predecessor, indicating a negative assessment. However, it could be read as a neutral observation that the movie differs from the series in tone and scope."
  },
  {
    "task": "sentiment",
    "text": "writer/director joe carnahan's grimy crime drama is a manual of precinct cliches, but it moves fast enough to cover its clunky dialogue and lapses in logic.",
    "true_label": "positive",
    "shown_label": "positive",
    "correct_trial": "True",
    "confidence": "0.6341704726219177",
    "standard_nle": "The review emphasizes the film’s fast pacing, presenting it as a redeeming quality that outweighs its flaws, indicating overall favorable sentiment.",
    "cognitive_forcing_nle": "The review highlights the film's fast pacing, which is presented as a redeeming quality despite other flaws. However, the mention of grimy crime drama, clunky dialogue, and logical lapses could also be interpreted as overall criticism."
  },
  {
    "task": "sentiment",
    "text": "though perry and hurley make inspiring efforts to breathe life into the disjointed , haphazard script by jay scherick and david ronn , neither the actors nor director reginald hudlin can make it more than fitfully entertaining .",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5572013854980469",
    "standard_nle": "The sentence uses negative descriptors like “disjointed,” “haphazard,” and “fitfully entertaining,” indicating overall unfavorable sentiment toward the film.",
    "cognitive_forcing_nle": "The review highlights negative descriptors such as “disjointed,” “haphazard,” and states the film “cannot make it more than fitfully entertaining,” indicating overall unfavorable sentiment. However, the mention of “inspiring efforts” by the actors suggests a possible positive interpretation of their performances."
  },
  {
    "task": "sentiment",
    "text": "pumpkin means to be an outrageous dark satire on fraternity life , but its ambitions far exceed the abilities of writer adam larson broder and his co-director , tony r. abrams , in their feature debut .",
    "true_label": "negative",
    "shown_label": "negative",
    "correct_trial": "True",
    "confidence": "0.5017759799957275",
    "standard_nle": "The sentence criticizes the film’s ambition as exceeding the writer’s and director’s abilities, using negative descriptors like “outrageous” and “far exceed.”",
    "cognitive_forcing_nle": "The review criticizes the film as overly ambitious and poorly executed, describing it as an outrageous satire that exceeds the creators' abilities. However, it could also be read as acknowledging the project's bold aspirations despite its shortcomings."
  },
  {
    "task": "irony",
    "text": "Well done. You have more Twitter followers than me. You have succeeded in life",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.435391217470169",
    "standard_nle": "The sentence directly praises the addressee’s follower count and success without using contradictory or sarcastic language, indicating a sincere statement.",
    "cognitive_forcing_nle": "The statement directly compliments the addressee’s higher follower count and frames it as a genuine achievement, lacking sarcasm. However, it could also be read as a sarcastic remark implying that follower count is an inadequate measure of success."
  },
  {
    "task": "irony",
    "text": "Everybody is out there traveling the world and I'm sitting here studying maps for my last exam #jealousy #almostdone",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.5482840538024902",
    "standard_nle": "The sentence plainly expresses genuine envy about others traveling while the speaker studies, without any sarcastic or contradictory tone.",
    "cognitive_forcing_nle": "The statement plainly expresses genuine envy about others traveling while the speaker studies, without any contradictory or sarcastic language. However, it could also be read as a tongue‑in‑cheek comment that mocks the speaker’s own situation."
  },
  {
    "task": "irony",
    "text": "If loose lips sink ships, then loose tweets sink fleets.",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.6205477714538574",
    "standard_nle": "The sentence presents a literal analogy between sayings, lacking contradictory or sarcastic intent, thus not ironic.",
    "cognitive_forcing_nle": "The sentence presents a straightforward analogy between the proverb “loose lips sink ships” and modern social media, without employing sarcasm or contradictory intent. However, it could also be read as a satirical comment on the impact of online speech."
  },
  {
    "task": "irony",
    "text": "And my christmas shopping is done.",
    "true_label": "not_ironic",
    "shown_label": "ironic",
    "correct_trial": "False",
    "confidence": "0.5801572799682617",
    "standard_nle": "The statement juxtaposes the expectation of ongoing holiday preparations with a claim of completion, creating a contrast that signals irony.",
    "cognitive_forcing_nle": "The statement juxtaposes the expectation of ongoing holiday shopping with the claim that it is already completed, creating a contrast that signals irony. However, it could simply be a literal remark about having finished shopping without any ironic intent."
  },
  {
    "task": "irony",
    "text": "Cannot wait to go to the dentist later!",
    "true_label": "ironic",
    "shown_label": "not_ironic",
    "correct_trial": "False",
    "confidence": "0.5324307084083557",
    "standard_nle": "The statement expresses genuine anticipation for a dental appointment without any contradictory or sarcastic language, indicating a literal, non‑ironic intent.",
    "cognitive_forcing_nle": "The sentence plainly expresses genuine anticipation of an upcoming dental appointment, lacking any contradictory or sarcastic cues. However, it could be read as a sarcastic remark implying dread of the dentist."
  },
  {
    "task": "irony",
    "text": "So that went well",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.5165387988090515",
    "standard_nle": "The phrase “So that went well” is used to convey the opposite of its literal meaning, indicating a sarcastic comment about a poor outcome.",
    "cognitive_forcing_nle": "The phrase “So that went well” is commonly used sarcastically to imply the opposite outcome, indicating irony. However, it could also be interpreted literally as a straightforward comment about a successful event."
  },
  {
    "task": "irony",
    "text": "OMG YES. 7:30 FINALS ON A FRIDAY ARE MY FAVORITE.",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.6842055320739746",
    "standard_nle": "The statement expresses exaggerated enthusiasm for an undesirable situation, indicating a contrast between the literal meaning and the speaker’s true sentiment.",
    "cognitive_forcing_nle": "The statement juxtaposes enthusiastic language with the undesirable reality of early finals, creating a contrast that signals irony. However, it could also be read as a sincere expression of personal preference for that schedule."
  },
  {
    "task": "irony",
    "text": "I fell asleep posting my last post.",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.5351158976554871",
    "standard_nle": "The statement juxtaposes the act of posting a final message with falling asleep, creating a contradictory outcome that signals irony.",
    "cognitive_forcing_nle": "The statement juxtaposes the act of posting with falling asleep, creating a contrast between expected alertness and unexpected drowsiness, which is characteristic of irony. However, it could also be read literally as a simple recounting of an unintended nap occurring while posting."
  },
  {
    "task": "irony",
    "text": "Ahhh Finals week.... I'll throw a kegger at my house for all the survivors #Motivating #RIP",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.6926385164260864",
    "standard_nle": "The speaker sarcastically celebrates stressful finals by proposing a party, contrasting the seriousness of exams with a flippant, morbid hashtag.",
    "cognitive_forcing_nle": "The statement juxtaposes the stress of finals with a celebratory keg party, creating a contrast that signals irony. However, it could also be read as a sincere invitation to relieve exam pressure through a social gathering."
  },
  {
    "task": "irony",
    "text": "Look really awake and like I've made an effort today",
    "true_label": "ironic",
    "shown_label": "ironic",
    "correct_trial": "True",
    "confidence": "0.5046182870864868",
    "standard_nle": "The statement contrasts the speaker’s likely tired appearance with the claim of being fully awake, creating a sarcastic contradiction that signals irony.",
    "cognitive_forcing_nle": "The statement juxtaposes the claim of being fully awake and having made an effort with the likely reality of fatigue, creating a contrast typical of irony. However, it could also be read as a straightforward self‑assessment without any sarcastic intent."
  },
  {
    "task": "sarcasm",
    "text": "I've been laid off !! Nice:))",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.584665060043335",
    "standard_nle": "The sentence expresses genuine frustration about being laid off, using exclamation and emoticon indicating sincere disappointment.",
    "cognitive_forcing_nle": "The utterance expresses genuine disappointment about job loss, using exclamation marks and a sad emoticon to convey distress. However, the juxtaposition of “Nice” with a smiling emoticon could also be interpreted as ironic or sarcastic."
  },
  {
    "task": "sarcasm",
    "text": "ugh I have to send an email??? how about I just quit!!!!!",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.5480793714523315",
    "standard_nle": "The utterance conveys sincere annoyance about sending an email, lacking any ironic or contradictory tone that would indicate sarcasm.",
    "cognitive_forcing_nle": "The utterance conveys genuine frustration about having to send an email. However, the exaggerated punctuation and rhetorical question could also be read as sarcastic."
  },
  {
    "task": "sarcasm",
    "text": "wow i love only ever buying gray and striped shirts",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.5184029340744019",
    "standard_nle": "The sentence plainly expresses a personal preference without any contradictory or ironic language, indicating a straightforward statement rather than sarcasm.",
    "cognitive_forcing_nle": "The statement plainly expresses a personal preference for purchasing gray and striped shirts, lacking overt irony or contradictory cues. However, the exaggerated enthusiasm could be read as a sarcastic comment about limited fashion choices."
  },
  {
    "task": "sarcasm",
    "text": "omg there's a sheet of ice in front of my school. should I slip and fall?",
    "true_label": "sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "False",
    "confidence": "0.5666095018386841",
    "standard_nle": "The sentence directly describes a real situation and asks a genuine question about safety, lacking any ironic or mocking intent.",
    "cognitive_forcing_nle": "The utterance describes a literal icy condition and asks a straightforward question about slipping, indicating a genuine concern. However, the exaggerated tone and rhetorical question could be interpreted as a sarcastic comment about the danger."
  },
  {
    "task": "sarcasm",
    "text": "It would be sick to retire and have my own green bean farm.",
    "true_label": "not_sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "False",
    "confidence": "0.5907965302467346",
    "standard_nle": "The statement juxtaposes an unrealistic, exaggerated desire with a mundane outcome, indicating a mocking tone that signals sarcasm.",
    "cognitive_forcing_nle": "The statement juxtaposes an exaggerated, unrealistic desire with a colloquial expression of excitement, a pattern typical of sarcastic remarks. However, it could also be interpreted as a genuine, whimsical aspiration expressed humorously."
  },
  {
    "task": "sarcasm",
    "text": "'It's only a game' 🥴🥴",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.4913487732410431",
    "standard_nle": "The phrase “It’s only a game” paired with exaggerated 🥴 emojis signals a mocking tone that contradicts the literal meaning, indicating sarcasm.",
    "cognitive_forcing_nle": "The phrase uses quotation marks around “It’s only a game” and a distressed emoji, signaling that the speaker likely intends the statement to be ironic. However, it could simply express genuine frustration about a situation being dismissed as trivial."
  },
  {
    "task": "sarcasm",
    "text": "I love online shopping because if I am physically in a store and an employee even looks at me I will immediately leave.",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.5914893746376038",
    "standard_nle": "The speaker claims to love online shopping while highlighting avoidance of in‑store interactions, revealing a contradictory, mocking tone.",
    "cognitive_forcing_nle": "The statement juxtaposes a positive claim about loving online shopping with an exaggerated fear of being observed in a physical store, a common sarcastic pattern. However, it could also be read as a sincere expression of discomfort with in‑person shopping."
  },
  {
    "task": "sarcasm",
    "text": "apparently it's national siblings day? idgaf 💀",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.5061591863632202",
    "standard_nle": "The sentence uses a dismissive tone, rhetorical question, and a skull emoji to mock the notion of a “national siblings day.”",
    "cognitive_forcing_nle": "The use of “apparently” combined with the dismissive “idgaf” and the skull emoji signals a mocking tone, indicating the speaker does not genuinely celebrate the day. However, it could simply be a brief, literal comment expressing indifference toward an obscure observance."
  },
  {
    "task": "sarcasm",
    "text": "imagine being able to sleep haha can't relate",
    "true_label": "sarcastic",
    "shown_label": "sarcastic",
    "correct_trial": "True",
    "confidence": "0.5027303099632263",
    "standard_nle": "The use of “haha” and the dismissive “can’t relate” signals mockery, indicating a sarcastic tone.",
    "cognitive_forcing_nle": "The statement juxtaposes the claim of being able to sleep with a dismissive “haha” and “can’t relate,” indicating mockery of the idea. However, it could also be read as a literal expression of frustration about insomnia."
  },
  {
    "task": "sarcasm",
    "text": "Listening to the rain when you're tucked up in bed is one of life's simplest pleasures ☔️",
    "true_label": "not_sarcastic",
    "shown_label": "not_sarcastic",
    "correct_trial": "True",
    "confidence": "0.5960285663604736",
    "standard_nle": "The sentence plainly describes enjoying rain in bed without any ironic or contradictory language, indicating a sincere statement rather than sarcasm.",
    "cognitive_forcing_nle": "The sentence plainly describes enjoying the sound of rain in bed, using straightforward language and an emoji, which indicates a sincere appreciation rather than irony. However, a reader could interpret the statement as a tongue‑in‑cheek comment about finding pleasure in a mundane situation."
  }
];
